#ifndef ROVER_4WS_CONFIG_H
#define ROVER_4WS_CONFIG_H

typedef enum
{
    ROVER_4WS_CONFIG_SERVO_0,
    ROVER_4WS_CONFIG_SERVO_1,
    ROVER_4WS_CONFIG_SERVO_2,
    ROVER_4WS_CONFIG_SERVO_3,
    ROVER_4WS_CONFIG_SERVO_MAX
} Rover4wsConfig_Servo_t;

#endif /* ROVER_4WS_CONFIG_H */